require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe SurveyFilesController do

  def mock_survey_file(stubs={})
    @mock_survey_file ||= mock_model(SurveyFile, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all survey_files as @survey_files" do
      SurveyFile.stub(:all) { [mock_survey_file] }
      get :index
      assigns(:survey_files).should eq([mock_survey_file])
    end
  end

  describe "GET show" do
    it "assigns the requested survey_file as @survey_file" do
      SurveyFile.stub(:find).with("37") { mock_survey_file }
      get :show, :id => "37"
      assigns(:survey_file).should be(mock_survey_file)
    end
  end

  describe "GET new" do
    it "assigns a new survey_file as @survey_file" do
      SurveyFile.stub(:new) { mock_survey_file }
      get :new
      assigns(:survey_file).should be(mock_survey_file)
    end
  end

  describe "GET edit" do
    it "assigns the requested survey_file as @survey_file" do
      SurveyFile.stub(:find).with("37") { mock_survey_file }
      get :edit, :id => "37"
      assigns(:survey_file).should be(mock_survey_file)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created survey_file as @survey_file" do
        SurveyFile.stub(:new).with({'these' => 'params'}) { mock_survey_file(:save => true) }
        post :create, :survey_file => {'these' => 'params'}
        assigns(:survey_file).should be(mock_survey_file)
      end

      it "redirects to the created survey_file" do
        SurveyFile.stub(:new) { mock_survey_file(:save => true) }
        post :create, :survey_file => {}
        response.should redirect_to(survey_file_url(mock_survey_file))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved survey_file as @survey_file" do
        SurveyFile.stub(:new).with({'these' => 'params'}) { mock_survey_file(:save => false) }
        post :create, :survey_file => {'these' => 'params'}
        assigns(:survey_file).should be(mock_survey_file)
      end

      it "re-renders the 'new' template" do
        SurveyFile.stub(:new) { mock_survey_file(:save => false) }
        post :create, :survey_file => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested survey_file" do
        SurveyFile.stub(:find).with("37") { mock_survey_file }
        mock_survey_file.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :survey_file => {'these' => 'params'}
      end

      it "assigns the requested survey_file as @survey_file" do
        SurveyFile.stub(:find) { mock_survey_file(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:survey_file).should be(mock_survey_file)
      end

      it "redirects to the survey_file" do
        SurveyFile.stub(:find) { mock_survey_file(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(survey_file_url(mock_survey_file))
      end
    end

    describe "with invalid params" do
      it "assigns the survey_file as @survey_file" do
        SurveyFile.stub(:find) { mock_survey_file(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:survey_file).should be(mock_survey_file)
      end

      it "re-renders the 'edit' template" do
        SurveyFile.stub(:find) { mock_survey_file(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested survey_file" do
      SurveyFile.stub(:find).with("37") { mock_survey_file }
      mock_survey_file.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the survey_files list" do
      SurveyFile.stub(:find) { mock_survey_file }
      delete :destroy, :id => "1"
      response.should redirect_to(survey_files_url)
    end
  end

end
